grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      objective: binary:logistic
      max_depth: 3
      min_child_weight: 1
    search_param_grid:
      max_depth:
      - 3
      - 5
      - 7
      - 9
      min_child_weight:
      - 1
      - 3
      - 5

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 10
    search_param_grid:
      max_depth:
      - 10
      - 12
      - null
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      - null
      n_estimators:
      - 10
      - 50
      - 100
      - 200

  module_2:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: kd_tree
      weights: uniform
      n_neighbors: 3
    search_param_grid:
      algorithm:
      - auto
      - ball_tree
      - kd_tree
      - brute
      weights:
      - uniform
      - distance
      n_neighbors:
      - 3
      - 4
      - 5
      - 7
      - 9

  module_3:
    class: CatBoostClassifier
    module: catboost
    params:
      verbose: 0
      iterations: 100
      learning_rate: 0.01
      depth: 4
    search_param_grid:
      iterations:
      - 100
      - 200
      - 300
      learning_rate:
      - 0.01
      - 0.1
      - 0.2
      depth:
      - 4
      - 6
      - 8
